### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by izaiasmachado** [izaiasmachado/yt-channel-data#1]
- [ ] Todo list

--- 

- [ ] Api credentials in a JSON
- [ ] Format data structure
- [ ] XMLHTTP script to request and fill the data structure
